version: "3"
services:
    mysql:
        platform: linux/x86_64
        image: mysql:8.0.30
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root_password"
            MYSQL_DATABASE: "outbox_messages"
            MYSQL_USER: "username"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_HOST: "0.0.0.0"
        ports:
            - "3306:3306"
    postgres:
        platform: linux/x86_64
        image: postgres:14-alpine3.16
        environment:
            POSTGRES_DB: "outbox_messages"
            POSTGRES_USER: "username"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"
