version: "3"
services:
    mysql:
        image: mysql:8.0.30
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "root_password"
            MYSQL_DATABASE: "outbox_messages"
            MYSQL_USER: "username"
            MYSQL_PASSWORD: "password"
            MYSQL_ROOT_HOST: "0.0.0.0"
        ports:
            - "3306:3306"
    postgres:
        image: postgres:14-alpine3.16
        restart: always
        environment:
            POSTGRES_DB: "outbox_messages"
            POSTGRES_USER: "username"
            POSTGRES_PASSWORD: "password"
        ports:
            - "5432:5432"

    php80: &base
      build:
        context: .
        args:
          PHP_VERSION: 8.0
      environment:
        EVENTSAUCE_TESTING_MYSQL_HOST: 'mysql'
        EVENTSAUCE_TESTING_PGSQL_HOST: 'postgres'
      profiles:
        - testing
      working_dir: /app
      volumes:
        - ./:/app

    php81:
      <<: *base
      build:
        args:
          PHP_VERSION: 8.1

    php82:
      <<: *base
      build:
        args:
          PHP_VERSION: 8.2

    php83:
      <<: *base
      build:
        args:
          PHP_VERSION: 8.3
